version: '3'

services:
  partyfy-api:
    image: partyfy-api:latest
    ports:
      - '4000:4000'
    networks:
      - partyfy-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      # - 443:443
    networks:
      - partyfy-network

networks:
  partyfy-network:
