version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.6.0
    steps:
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
